
# 	Trevor Berggren
#	z1906236
#	CSCI 340 
#	I certify that this is my own work and where appropriate an extension 
#	of the starter code provided for the assignment.

 wordscanner: wordscanner.cc wordscanner.h 
	g++ -std=c++11 -Wall -Wextra -pedantic -o wordscanner wordscanner.cc 

clean:
	rm wordscanner
