# 	Trevor Berggren
#	z1906236
#	CSCI 340 
#	I certify that this is my own work and where appropriate an extension 
#	of the starter code provided for the assignment.

 binarytree: binarytree.cc btree.h node.h 
	g++ -std=c++11 -Wall -Wextra -pedantic -o binarytree binarytree.cc 

clean:
	rm binarytree
