# 	Trevor Berggren
#	z1906236
#	CSCI 340 
#	I certify that this is my own work and where appropriate an extension 
#	of the starter code provided for the assignment.

 hash: hashmain.cc htable.cc hashmain.h entry.h  htable.h 
	g++ -std=c++11 -Wall -Wextra -pedantic -o hash hashmain.cc htable.cc

clean:
	rm hash
